config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :campaigns
  resources :flightclasses
  resources :cities
  get 'jalpoint', to: 'jalpoint#index'
  post 'jalpoint', to: 'jalpoint#index'
  get 'jalpoint/index'
  post 'jalpoint/index'
  get 'jalpoint/edit/:id', to: 'jalpoint#edit'
  post 'jalpoint/edit/:id', to: 'jalpoint#update'
  patch 'jalpoint/edit/:id', to: 'jalpoint#update'
  get 'jalpoint/delete/:id', to: 'jalpoint#delete'
  get "jalpoint/calpoint"
  get 'jalpoint', to: 'jalpoint#calpoint'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/flightclasses_controller.rb
class FlightclassesController < ApplicationController
  before_action :set_flightclass, only: [:show, :edit, :update, :destroy]

  # GET /flightclasses
  # GET /flightclasses.json
  def index
    @flightclasses = Flightclass.all
  end

  # GET /flightclasses/1
  # GET /flightclasses/1.json
  def show
  end

  # GET /flightclasses/new
  def new
    @flightclass = Flightclass.new
  end

  # GET /flightclasses/1/edit
  def edit
  end

  # POST /flightclasses
  # POST /flightclasses.json
  def create
    @flightclass = Flightclass.new(flightclass_params)

    respond_to do |format|
      if @flightclass.save
        format.html { redirect_to @flightclass, notice: 'Flightclass was successfully created.' }
        format.json { render :show, status: :created, location: @flightclass }
      else
        format.html { render :new }
        format.json { render json: @flightclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flightclasses/1
  # PATCH/PUT /flightclasses/1.json
  def update
    respond_to do |format|
      if @flightclass.update(flightclass_params)
        format.html { redirect_to @flightclass, notice: 'Flightclass was successfully updated.' }
        format.json { render :show, status: :ok, location: @flightclass }
      else
        format.html { render :edit }
        format.json { render json: @flightclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flightclasses/1
  # DELETE /flightclasses/1.json
  def destroy
    @flightclass.destroy
    respond_to do |format|
      format.html { redirect_to flightclasses_url, notice: 'Flightclass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flightclass
      @flightclass = Flightclass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flightclass_params
      params.require(:flightclass).permit(:flightclass, :classcode, :addon)
    end
end

app/helpers/flightclasses_helper.rb
module FlightclassesHelper
end

app/views/flightclasses/_form.html.erb
<%= form_for(flightclass) do |f| %>
  <% if flightclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flightclass.errors.count, "error") %> prohibited this flightclass from being saved:</h2>

      <ul>
      <% flightclass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flightclass %>
    <%= f.text_field :flightclass %>
  </div>

  <div class="field">
    <%= f.label :classcode %>
    <%= f.text_field :classcode %>
  </div>

  <div class="field">
    <%= f.label :addon %>
    <%= f.number_field :addon %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flightclasses/edit.html.erb
<h1>Editing Flightclass</h1>

<%= render 'form', flightclass: @flightclass %>

<%= link_to 'Show', @flightclass %> |
<%= link_to 'Back', flightclasses_path %>

app/views/flightclasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flightclasses</h1>

<table>
  <thead>
    <tr>
      <th>Flightclass</th>
      <th>Classcode</th>
      <th>Addon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flightclasses.each do |flightclass| %>
      <tr>
        <td><%= flightclass.flightclass %></td>
        <td><%= flightclass.classcode %></td>
        <td><%= flightclass.addon %></td>
        <td><%= link_to 'Show', flightclass %></td>
        <td><%= link_to 'Edit', edit_flightclass_path(flightclass) %></td>
        <td><%= link_to 'Destroy', flightclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flightclass', new_flightclass_path %>

<br>
<br>
<%= link_to 'JalPointManage', '/jalpoint' %>

app/views/flightclasses/new.html.erb
<h1>New Flightclass</h1>

<%= render 'form', flightclass: @flightclass %>

<%= link_to 'Back', flightclasses_path %>

app/views/flightclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flightclass:</strong>
  <%= @flightclass.flightclass %>
</p>

<p>
  <strong>Classcode:</strong>
  <%= @flightclass.classcode %>
</p>

<p>
  <strong>Addon:</strong>
  <%= @flightclass.addon %>
</p>

<%= link_to 'Edit', edit_flightclass_path(@flightclass) %> |
<%= link_to 'Back', flightclasses_path %>