config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :campaigns
  resources :flightclasses
  resources :cities
  get 'jalpoint', to: 'jalpoint#index'
  post 'jalpoint', to: 'jalpoint#index'
  get 'jalpoint/index'
  post 'jalpoint/index'
  get 'jalpoint/edit/:id', to: 'jalpoint#edit'
  post 'jalpoint/edit/:id', to: 'jalpoint#update'
  patch 'jalpoint/edit/:id', to: 'jalpoint#update'
  get 'jalpoint/delete/:id', to: 'jalpoint#delete'
  get "jalpoint/calpoint"
  get 'jalpoint', to: 'jalpoint#calpoint'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:ctype, :ctypedetail, :bway, :bpoint)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ctype %>
    <%= f.text_field :ctype %>
  </div>

  <div class="field">
    <%= f.label :ctypedetail %>
    <%= f.text_field :ctypedetail %>
  </div>

  <div class="field">
    <%= f.label :bway %>
    <%= f.text_field :bway %>
  </div>

  <div class="field">
    <%= f.label :bpoint %>
    <%= f.text_field :bpoint %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Ctype</th>
      <th>Ctypedetail</th>
      <th>Bway</th>
      <th>Bpoint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.ctype %></td>
        <td><%= campaign.ctypedetail %></td>
        <td><%= campaign.bway %></td>
        <td><%= campaign.bpoint %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>
<br>
<br>
<%= link_to 'JalPointManage', '/jalpoint' %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ctype:</strong>
  <%= @campaign.ctype %>
</p>

<p>
  <strong>Ctypedetail:</strong>
  <%= @campaign.ctypedetail %>
</p>

<p>
  <strong>Bway:</strong>
  <%= @campaign.bway %>
</p>

<p>
  <strong>Bpoint:</strong>
  <%= @campaign.bpoint %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>